---
          - name: Installing apache2 package
            apt:
                    name=apache2
                    state=present
            when:
                    ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'


          - name: Installing httpd package
            yum:
                    name=httpd
                    state=latest
            when:
                    ansible_distribution == 'Centos' or ansible_distribution == 'Redhat' or ansible_distribution == 'Amazon Linux'

